// 샘플 스토리 데이터

export const createSampleStory = () => {
  const sampleNodes = [
    {
      id: '1',
      type: 'default',
      data: { 
        label: '왕국의 시작',
        story: '당신은 새로운 왕국의 통치자가 되었습니다. 백성들이 당신을 바라보고 있습니다. 첫 번째 결정을 내려야 할 때입니다.',
        choice: '',
        statChanges: { health: 0, wealth: 0, happiness: 0, power: 0 }
      },
      position: { x: 250, y: 50 },
      style: {
        background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
        color: 'white',
        border: '3px solid #ffd700',
        width: 160,
        height: 80,
        borderRadius: '16px',
        fontSize: '13px',
        fontWeight: '600',
        boxShadow: '0 8px 32px rgba(0, 0, 0, 0.2), 0 0 20px rgba(255, 215, 0, 0.5)',
        backdropFilter: 'blur(10px)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        textAlign: 'center',
        padding: '12px',
        textShadow: '0 2px 4px rgba(0, 0, 0, 0.3)',
        transition: 'all 0.3s ease',
        cursor: 'pointer',
      },
    },
    {
      id: '2',
      type: 'default',
      data: { 
        label: '세금 인상',
        story: '재정이 부족합니다. 세금을 인상하여 국고를 채우시겠습니까? 백성들은 불만을 표할 수 있지만 국가 운영에는 도움이 될 것입니다.',
        choice: '세금을 인상한다',
        statChanges: { health: 0, wealth: 10, happiness: -5, power: 5 }
      },
      position: { x: 100, y: 200 },
      style: {
        background: 'linear-gradient(135deg, #fa709a 0%, #fee140 100%)',
        color: 'white',
        border: '2px solid rgba(255, 255, 255, 0.2)',
        width: 160,
        height: 80,
        borderRadius: '16px',
        fontSize: '13px',
        fontWeight: '600',
        boxShadow: '0 8px 32px rgba(0, 0, 0, 0.2)',
        backdropFilter: 'blur(10px)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        textAlign: 'center',
        padding: '12px',
        textShadow: '0 2px 4px rgba(0, 0, 0, 0.3)',
        transition: 'all 0.3s ease',
        cursor: 'pointer',
      },
    },
    {
      id: '3',
      type: 'default',
      data: { 
        label: '축제 개최',
        story: '백성들의 사기를 높이기 위해 대규모 축제를 개최하시겠습니까? 비용이 많이 들지만 백성들의 행복도가 크게 증가할 것입니다.',
        choice: '축제를 개최한다',
        statChanges: { health: 0, wealth: -10, happiness: 15, power: 0 }
      },
      position: { x: 400, y: 200 },
      style: {
        background: 'linear-gradient(135deg, #43e97b 0%, #38f9d7 100%)',
        color: 'white',
        border: '2px solid rgba(255, 255, 255, 0.2)',
        width: 160,
        height: 80,
        borderRadius: '16px',
        fontSize: '13px',
        fontWeight: '600',
        boxShadow: '0 8px 32px rgba(0, 0, 0, 0.2)',
        backdropFilter: 'blur(10px)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        textAlign: 'center',
        padding: '12px',
        textShadow: '0 2px 4px rgba(0, 0, 0, 0.3)',
        transition: 'all 0.3s ease',
        cursor: 'pointer',
      },
    },
    {
      id: '4',
      type: 'default',
      data: { 
        label: '백성의 반란',
        story: '세금 인상으로 인해 백성들이 반란을 일으켰습니다! 강경하게 진압하시겠습니까, 아니면 협상을 시도하시겠습니까?',
        choice: '',
        statChanges: { health: -10, wealth: 0, happiness: -10, power: -5 }
      },
      position: { x: 50, y: 350 },
      style: {
        background: 'linear-gradient(135deg, #f093fb 0%, #f5576c 100%)',
        color: 'white',
        border: '2px solid rgba(255, 255, 255, 0.2)',
        width: 160,
        height: 80,
        borderRadius: '16px',
        fontSize: '13px',
        fontWeight: '600',
        boxShadow: '0 8px 32px rgba(0, 0, 0, 0.2)',
        backdropFilter: 'blur(10px)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        textAlign: 'center',
        padding: '12px',
        textShadow: '0 2px 4px rgba(0, 0, 0, 0.3)',
        transition: 'all 0.3s ease',
        cursor: 'pointer',
      },
    },
    {
      id: '5',
      type: 'default',
      data: { 
        label: '경제 성장',
        story: '세금 수입으로 인프라를 개선했습니다. 경제가 성장하고 있지만 여전히 백성들의 불만이 남아있습니다.',
        choice: '인프라에 투자한다',
        statChanges: { health: 5, wealth: 15, happiness: 5, power: 5 }
      },
      position: { x: 150, y: 350 },
      style: {
        background: 'linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)',
        color: 'white',
        border: '2px solid rgba(255, 255, 255, 0.2)',
        width: 160,
        height: 80,
        borderRadius: '16px',
        fontSize: '13px',
        fontWeight: '600',
        boxShadow: '0 8px 32px rgba(0, 0, 0, 0.2)',
        backdropFilter: 'blur(10px)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        textAlign: 'center',
        padding: '12px',
        textShadow: '0 2px 4px rgba(0, 0, 0, 0.3)',
        transition: 'all 0.3s ease',
        cursor: 'pointer',
      },
    },
    {
      id: '6',
      type: 'default',
      data: { 
        label: '행복한 백성',
        story: '축제가 대성공을 거두었습니다! 백성들이 매우 행복해하며 당신의 통치를 지지하고 있습니다. 하지만 국고가 부족해졌습니다.',
        choice: '',
        statChanges: { health: 0, wealth: -5, happiness: 20, power: 10 }
      },
      position: { x: 350, y: 350 },
      style: {
        background: 'linear-gradient(135deg, #a8edea 0%, #fed6e3 100%)',
        color: 'white',
        border: '2px solid rgba(255, 255, 255, 0.2)',
        width: 160,
        height: 80,
        borderRadius: '16px',
        fontSize: '13px',
        fontWeight: '600',
        boxShadow: '0 8px 32px rgba(0, 0, 0, 0.2)',
        backdropFilter: 'blur(10px)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        textAlign: 'center',
        padding: '12px',
        textShadow: '0 2px 4px rgba(0, 0, 0, 0.3)',
        transition: 'all 0.3s ease',
        cursor: 'pointer',
      },
    },
    {
      id: '7',
      type: 'default',
      data: { 
        label: '외교 동맹',
        story: '이웃 왕국에서 동맹을 제안했습니다. 경제적 지원을 받을 수 있지만 군사적 의무도 따릅니다.',
        choice: '동맹을 맺는다',
        statChanges: { health: 0, wealth: 10, happiness: 0, power: 15 }
      },
      position: { x: 450, y: 350 },
      style: {
        background: 'linear-gradient(135deg, #ff9a9e 0%, #fecfef 100%)',
        color: 'white',
        border: '2px solid rgba(255, 255, 255, 0.2)',
        width: 160,
        height: 80,
        borderRadius: '16px',
        fontSize: '13px',
        fontWeight: '600',
        boxShadow: '0 8px 32px rgba(0, 0, 0, 0.2)',
        backdropFilter: 'blur(10px)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        textAlign: 'center',
        padding: '12px',
        textShadow: '0 2px 4px rgba(0, 0, 0, 0.3)',
        transition: 'all 0.3s ease',
        cursor: 'pointer',
      },
    },
    {
      id: '8',
      type: 'default',
      data: { 
        label: '강경 진압',
        story: '반란을 강경하게 진압했습니다. 질서는 회복되었지만 백성들의 원한이 깊어졌습니다. 권력은 강화되었습니다.',
        choice: '군대를 동원한다',
        statChanges: { health: -5, wealth: 0, happiness: -15, power: 20 }
      },
      position: { x: 0, y: 500 },
      style: {
        background: 'linear-gradient(135deg, #ffecd2 0%, #fcb69f 100%)',
        color: 'white',
        border: '2px solid rgba(255, 255, 255, 0.2)',
        width: 160,
        height: 80,
        borderRadius: '16px',
        fontSize: '13px',
        fontWeight: '600',
        boxShadow: '0 8px 32px rgba(0, 0, 0, 0.2)',
        backdropFilter: 'blur(10px)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        textAlign: 'center',
        padding: '12px',
        textShadow: '0 2px 4px rgba(0, 0, 0, 0.3)',
        transition: 'all 0.3s ease',
        cursor: 'pointer',
      },
    },
    {
      id: '9',
      type: 'default',
      data: { 
        label: '평화 협상',
        story: '백성들과 협상하여 세금을 일부 인하했습니다. 평화는 찾았지만 재정 상황이 더욱 어려워졌습니다.',
        choice: '협상을 시도한다',
        statChanges: { health: 5, wealth: -10, happiness: 10, power: -5 }
      },
      position: { x: 100, y: 500 },
      style: {
        background: 'linear-gradient(135deg, #ff8a80 0%, #ea6100 100%)',
        color: 'white',
        border: '2px solid rgba(255, 255, 255, 0.2)',
        width: 160,
        height: 80,
        borderRadius: '16px',
        fontSize: '13px',
        fontWeight: '600',
        boxShadow: '0 8px 32px rgba(0, 0, 0, 0.2)',
        backdropFilter: 'blur(10px)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        textAlign: 'center',
        padding: '12px',
        textShadow: '0 2px 4px rgba(0, 0, 0, 0.3)',
        transition: 'all 0.3s ease',
        cursor: 'pointer',
      },
    }
  ];

  const sampleEdges = [
    { id: 'e1-2', source: '1', target: '2', type: 'smoothstep' },
    { id: 'e1-3', source: '1', target: '3', type: 'smoothstep' },
    { id: 'e2-4', source: '2', target: '4', type: 'smoothstep' },
    { id: 'e2-5', source: '2', target: '5', type: 'smoothstep' },
    { id: 'e3-6', source: '3', target: '6', type: 'smoothstep' },
    { id: 'e3-7', source: '3', target: '7', type: 'smoothstep' },
    { id: 'e4-8', source: '4', target: '8', type: 'smoothstep' },
    { id: 'e4-9', source: '4', target: '9', type: 'smoothstep' },
  ];

  return { nodes: sampleNodes, edges: sampleEdges };
};

export const createFantasyAdventureStory = () => {
  const nodes = [
    {
      id: '1',
      type: 'default',
      data: { 
        label: '신비한 숲',
        story: '당신은 모험가입니다. 신비한 숲에서 갈래길을 만났습니다. 어느 길로 가시겠습니까?',
        choice: '',
        statChanges: { health: 0, wealth: 0, happiness: 0, power: 0 }
      },
      position: { x: 250, y: 50 },
      style: {
        background: 'linear-gradient(135deg, #84fab0 0%, #8fd3f4 100%)',
        color: 'white',
        border: '3px solid #ffd700',
        width: 160,
        height: 80,
        borderRadius: '16px',
        fontSize: '13px',
        fontWeight: '600',
        boxShadow: '0 8px 32px rgba(0, 0, 0, 0.2), 0 0 20px rgba(255, 215, 0, 0.5)',
        backdropFilter: 'blur(10px)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        textAlign: 'center',
        padding: '12px',
        textShadow: '0 2px 4px rgba(0, 0, 0, 0.3)',
        transition: 'all 0.3s ease',
        cursor: 'pointer',
      },
    },
    {
      id: '2',
      type: 'default',
      data: { 
        label: '어두운 동굴',
        story: '어두운 동굴 입구에 도착했습니다. 안에서 이상한 소리가 들립니다. 들어가시겠습니까?',
        choice: '어두운 길로 간다',
        statChanges: { health: -5, wealth: 0, happiness: -5, power: 5 }
      },
      position: { x: 100, y: 200 },
      style: {
        background: 'linear-gradient(135deg, #a6c1ee 0%, #fbc2eb 100%)',
        color: 'white',
        border: '2px solid rgba(255, 255, 255, 0.2)',
        width: 160,
        height: 80,
        borderRadius: '16px',
        fontSize: '13px',
        fontWeight: '600',
        boxShadow: '0 8px 32px rgba(0, 0, 0, 0.2)',
        backdropFilter: 'blur(10px)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        textAlign: 'center',
        padding: '12px',
        textShadow: '0 2px 4px rgba(0, 0, 0, 0.3)',
        transition: 'all 0.3s ease',
        cursor: 'pointer',
      },
    },
    {
      id: '3',
      type: 'default',
      data: { 
        label: '밝은 초원',
        story: '아름다운 초원에 도착했습니다. 멀리서 요정들이 춤추는 모습이 보입니다. 다가가시겠습니까?',
        choice: '밝은 길로 간다',
        statChanges: { health: 5, wealth: 0, happiness: 10, power: 0 }
      },
      position: { x: 400, y: 200 },
      style: {
        background: 'linear-gradient(135deg, #fdcbf1 0%, #fdcbf1 100%)',
        color: 'white',
        border: '2px solid rgba(255, 255, 255, 0.2)',
        width: 160,
        height: 80,
        borderRadius: '16px',
        fontSize: '13px',
        fontWeight: '600',
        boxShadow: '0 8px 32px rgba(0, 0, 0, 0.2)',
        backdropFilter: 'blur(10px)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        textAlign: 'center',
        padding: '12px',
        textShadow: '0 2px 4px rgba(0, 0, 0, 0.3)',
        transition: 'all 0.3s ease',
        cursor: 'pointer',
      },
    }
  ];

  const edges = [
    { id: 'e1-2', source: '1', target: '2', type: 'smoothstep' },
    { id: 'e1-3', source: '1', target: '3', type: 'smoothstep' }
  ];

  return { nodes, edges };
};
